services:
  web:
    build:
      context: .
      dockerfile: src/PracticalWork.Library.Web/Dockerfile
    container_name: library_web
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      App__DbConnectionString: "Host=postgres;Port=5432;Database=BookArchiveDb;Username=postgres;Password=myhome1861"
      App__DbConnectionStringReport: "Host=postgres-reports;Port=5432;Database=reports;Username=postgres;Password=myhome1861"
      App__Redis__RedisCacheConnection: "redis:6379"
      App__Minio__Endpoint: "minio:9000"
      App__Minio__AccessKey: "minioadmin"
      App__Minio__SecretKey: "minioadmin"
      App__Minio__BucketName: "reports"
      App__Minio__ReportsBucketName: "reports"
      App__Minio__LibraryReportsBucketName: "library-reports"
      App__RabbitMQ__Host: "rabbitmq"
      App__RabbitMQ__User: "guest"
      App__RabbitMQ__Password: "guest"
      App__RabbitMQ__Port: "5672"
      App__Email__SmtpServer: "smtp4dev"
      App__Email__SmtpPort: "25"
      App__Email__UseSsl: "false"
      App__Email__SenderName: "Библиотека"
      App__Email__SenderEmail: "noreply@library.local"
    depends_on:
      postgres:
        condition: service_healthy
      postgres-reports:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: library_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myhome1861
      POSTGRES_DB: BookArchiveDb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_library:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-reports:
    image: postgres:15
    container_name: reports_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myhome1861
      POSTGRES_DB: reports
    ports:
      - "5434:5432"
    volumes:
      - pgdata_reports:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: library_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: library_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: library-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: library_smtp4dev
    restart: unless-stopped
    ports:
      - "5001:80"
      - "25:25"
      - "143:143"
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  pgdata_library:
    driver: local
  pgdata_reports:
    driver: local
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local
